spring:

  profiles:
    active: local

  datasource:
    username: postgres
    password: ${db-password}
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
